FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/
COPY data/raw/train_set.csv ./data/raw/train_set.csv

ENV PYTHONPATH=/app