services:
  preprocessing:
    build:
      context: .
      dockerfile: Dockerfile.preprocessing
    volumes:
      - ./data/processed:/app/data/processed
      - ./data/raw:/app/data/raw
    command: python src/pipelines/run_preprocessing.py
    depends_on: []

  modelling:
    build:
      context: .
      dockerfile: Dockerfile.modelling
    volumes:
      - ./data/processed:/app/data/processed
      - ./src:/app/src
      - mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: python src/pipelines/run_modelling.py
    depends_on:
      - preprocessing
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.2.2
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_ARTIFACT_ROOT=/mlruns
    volumes:
      - mlruns:/mlruns
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns --host 0.0.0.0

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./data/processed:/app/data/processed
    depends_on:
      - modelling

volumes:
  mlruns: