FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/
COPY src/ ./src/

ENV PYTHONPATH=/app

COPY wait-for-files-api.sh /wait-for-files-api.sh
RUN chmod +x /wait-for-files-api.sh
CMD ["/wait-for-files-api.sh"]