FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

## added to export metric
RUN pip install prometheus_client==0.20.0  

COPY app/ ./app/
COPY src/ ./src/

ENV PYTHONPATH=/app

CMD ["uvicorn", "src.api.basicAPI:app", "--host", "0.0.0.0", "--port", "8000"]