FROM python:3.10-slim

WORKDIR /app

# Install Dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy Source and Configurations
COPY src/ ./src/
COPY params.yaml dvc.yaml dvc.lock ./
COPY data/ ./data/

ENV PYTHONPATH=/app

CMD ["python", "src/pipelines/run_modelling.py"]